# Generated by Django 5.2.13 on 2026-04-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "relationship",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelmetDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(default="SmartHelmetX", max_length=100)),
                ("ble_mac", models.CharField(blank=True, default="", max_length=17)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("pairing", "Pairing"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                ("battery_level", models.IntegerField(default=100)),
                ("firmware_version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "fall_threshold",
                    models.FloatField(
                        default=1.8, help_text="G-force threshold for fall detection"
                    ),
                ),
                (
                    "no_move_timeout",
                    models.IntegerField(
                        default=8000, help_text="No movement timeout in ms"
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("fall", "Fall Detected"),
                            ("sos", "SOS Triggered"),
                            ("no_movement", "No Movement"),
                            ("impact", "High Impact"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("message", models.TextField(default="")),
                (
                    "acc_magnitude",
                    models.FloatField(
                        default=0, help_text="Acceleration magnitude at time of alert"
                    ),
                ),
                ("sms_sent", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.helmetdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GPSLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed", models.FloatField(default=0, help_text="Speed in km/h")),
                ("altitude", models.FloatField(default=0)),
                (
                    "accuracy",
                    models.FloatField(default=0, help_text="GPS accuracy in meters"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="api.helmetdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="api_gpsloca_device__3e0602_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("acc_x", models.FloatField(default=0)),
                ("acc_y", models.FloatField(default=0)),
                ("acc_z", models.FloatField(default=1.0)),
                ("gyro_x", models.FloatField(default=0)),
                ("gyro_y", models.FloatField(default=0)),
                ("gyro_z", models.FloatField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="api.helmetdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="api_sensorr_device__f6ddd2_idx",
                    )
                ],
            },
        ),
    ]
